Repository apimatic/go-core-runtime, pull requests merged in 2024-03, with the labels that each got.

#64 perf(go): refactor code for JSON body and query parameters handling
  https/callBuilder.go
  https/callBuilder_test.go
  https/formData.go
  https/formData_test.go
  testHelper/bodyMatchers.go
  utilities/apiHelper.go
  utilities/apiHelper_test.go
Labels: enhancement, priority-high, refactoring

#66 fix(body-matchers): made body matcher functions generic for valid marshalling
  .gitignore
  testHelper/bodyMatchers.go
  testHelper/bodyMatchers_test.go
Labels: bug

#71 fix: invalid content-type for arrays in request body
  https/callBuilder.go
  testHelper/bodyMatchers.go
  testHelper/bodyMatchers_test.go
Labels: bug

#74 refactor(go): add support for Date time format for OAF classes
  utilities/internal_time_types.go
  utilities/internal_time_types_test.go
Labels: enhancement, priority-high

#77 refactor(go): removed jsonpointer dependency and refactored existing unit test
  go.mod
  go.sum
  https/apiError.go
  https/rawJsonPointer.go
Labels: enhancement, priority-high, refactoring
